---
name: mysql

update:
  canaries: 1
  canary_watch_time: 10000-600000
  update_watch_time: 10000-600000
  max_in_flight: 1
  serial: true

instance_groups:
- name: mysql
  instances: 2
  azs: [dc1_z1, dc2_z1]
  networks: [{name: default}]
  vm_type: large
  stemcell: default
  persistent_disk: 10000
  jobs:
  - name: mysql
    release: cf-mysql-custom
    properties:
      cf_mysql:
        mysql:
          admin_password: ((cf_mysql_mysql_admin_password))
          remote_admin_access: true
          cluster_health:
            password: ((cf_mysql_mysql_cluster_health_password))
          galera_healthcheck:
            endpoint_password: ((cf_mysql_mysql_galera_healthcheck_endpoint_password))
            db_password: ((cf_mysql_mysql_galera_healthcheck_db_password))
  - name: smoke-tests-user
    release: cf-mysql-custom
    properties:
      cf_mysql:
        smoke_tests:
          db_password: ((cf_mysql_smoke_tests_db_password))

- name: arbitrator
  instances: 1
  azs: [dc1_z1]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - release: cf-mysql-custom
    name: arbitrator
    properties:
      cf_mysql:
        mysql:
          admin_password: ((cf_mysql_mysql_admin_password))
          galera_healthcheck:
            endpoint_password: ((cf_mysql_mysql_galera_healthcheck_endpoint_password))

- name: proxy
  instances: 2
  azs: [dc1_z1, dc2_z1]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - name: proxy
    release: cf-mysql-custom
    properties:
      cf_mysql:
        proxy:
          api_password: ((cf_mysql_proxy_api_password))
    provides:
      mysql-database:
        as: mysql-database
        shared: true

- name: bootstrap-vm
  instances: 1
  lifecycle: errand
  azs: [dc1_z1]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - {release: cf-mysql-custom, name: bootstrap}

- name: rejoin-unsafe-vm
  instances: 1
  lifecycle: errand
  azs: [dc1_z1]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - {release: cf-mysql-custom, name: rejoin-unsafe}

- name: verify-cluster-schemas-vm
  instances: 1
  lifecycle: errand
  azs: [dc1_z1]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - name: verify-cluster-schemas
    release: cf-mysql-custom
    properties:
      cf_mysql:
        mysql:
          admin_password: ((cf_mysql_mysql_admin_password))
          galera_healthcheck:
            endpoint_password: ((cf_mysql_mysql_galera_healthcheck_endpoint_password))

- name: smoke-tests-vm
  instances: 1
  lifecycle: errand
  azs: [dc1_z1]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - name: smoke-tests
    release: cf-mysql-custom
    properties:
      cf_mysql:
        mysql:
          admin_password: ((cf_mysql_mysql_admin_password))
        proxy:
          api_password: ((cf_mysql_proxy_api_password))
        smoke_tests:
          db_password: ((cf_mysql_smoke_tests_db_password))
          standalone_tests_only: true

variables:
- name: cf_mysql_mysql_admin_password
  type: password
- name: cf_mysql_mysql_cluster_health_password
  type: password
- name: cf_mysql_mysql_galera_healthcheck_db_password
  type: password
- name: cf_mysql_mysql_galera_healthcheck_endpoint_password
  type: password
- name: cf_mysql_proxy_api_password
  type: password
- name: cf_mysql_smoke_tests_db_password
  type: password

stemcells:
- alias: default
  os: ubuntu-trusty
  version: "3586.7"
