resources:
- name: concourse-mysql-deployment
  type: git
  source:
    uri: {{concourse-mysql-deployment-git-url}}
    private_key: ((git_private_key))
- name: mysql-version
  type: concourse-version-resource

- name: mysql-release-version
  type: concourse-version-resource

- name: telegraf-agent-version
  type: concourse-version-resource

- name: proxy-version
  type: concourse-version-resource

- name: stemcell-version
  type: concourse-version-resource

- name: daily
  type: time
  source: {interval: 24h}


resource_types:
- name: concourse-version-resource
  type: docker-image
  source:
    repository: meteogroup/concourse-version-resource
    tag: latest


jobs:
- name: build-mysql-release
  plan:
    - aggregate:
      - get: concourse-mysql-deployment
    - task: build-mysql-release
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/docker-cfbosh
            tag: latest
        run:
          path: concourse-mysql-deployment/ci/tasks/build-mysql-release.sh 
        params:
          BOSH_CLIENT: ((bosh_client)) 
          BOSH_CLIENT_SECRET: ((bosh_client_secret))
          BOSH_CA_CERT: ((bosh_ca_cert))
          BOSH_ENVIRONMENT: ((bosh_environment))
          CF_MYSQL_RELEASE_URL: {{cf_mysql_release_url}}
          CF_MYSQL_RELEASE_TAG: {{cf_mysql_release_tag}}
          CF_MYSQL_BROKER_URL: {{cf_mysql_broker_url}}
        inputs:
        - name: concourse-mysql-deployment
    - put: mysql-release-version

- name: build-telegraf-agent-release
  plan:
    - aggregate:
      - get: concourse-mysql-deployment
    - task: build-telegraf-agent-release
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/docker-cfbosh
            tag: latest
        run:
          path: concourse-mysql-deployment/ci/tasks/build-telegraf-agent-release.sh 
        params:
          BOSH_CLIENT: ((bosh_client)) 
          BOSH_CLIENT_SECRET: ((bosh_client_secret))
          BOSH_CA_CERT: ((bosh_ca_cert))
          BOSH_ENVIRONMENT: ((bosh_environment))
          TELEGRAF_AGENT_RELEASE_URL: {{telegraf_agent_release_url}}
        inputs:
        - name: concourse-mysql-deployment
    - put: telegraf-agent-version

- name: upload-proxy-release
  plan:
    - aggregate:
      - get: concourse-mysql-deployment
    - task: upload-proxy-release
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/docker-cfbosh
            tag: latest
        run:
          path: concourse-mysql-deployment/ci/tasks/upload-proxy-release.sh 
        params:
          BOSH_CLIENT: ((bosh_client)) 
          BOSH_CLIENT_SECRET: ((bosh_client_secret))
          BOSH_CA_CERT: ((bosh_ca_cert))
          BOSH_ENVIRONMENT: ((bosh_environment))
          WAVEFRONT_PROXY_RELEASE_URL: {{wavefront_proxy_release_url}}
        inputs:
        - name: concourse-mysql-deployment
    - put: proxy-version

- name: upload-stemcell
  plan:
    - aggregate:
      - get: concourse-mysql-deployment
    - task: upload-stemcell
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/docker-cfbosh
            tag: latest
        run:
          path: concourse-mysql-deployment/ci/tasks/upload-stemcell.sh 
        params:
          BOSH_CLIENT: ((bosh_client)) 
          BOSH_CLIENT_SECRET: ((bosh_client_secret))
          BOSH_CA_CERT: ((bosh_ca_cert))
          BOSH_ENVIRONMENT: ((bosh_environment))
          STEMCELL_URL: {{stemcell_url}}
          STEMCELL_VERSION: {{stemcell_version}}
        inputs:
        - name: concourse-mysql-deployment
    - put: stemcell-version

- name: deploy 
  plan:
    - aggregate:
      - get: mysql-release-version 
        passed: [build-mysql-release]
        trigger: true
      - get: telegraf-agent-version 
        passed: [build-telegraf-agent-release]
        trigger: true
      - get: proxy-version 
        passed: [upload-proxy-release]
        trigger: true
      - get: stemcell-version 
        passed: [upload-stemcell]
        trigger: true
      - get: concourse-mysql-deployment
    - task: deploy
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: smatyukevich/docker-cfbosh 
            tag: latest
        run:
          path: concourse-mysql-deployment/ci/tasks/deploy-mysql.sh 
        params:
          VAULT_ADDR: {{vault-addr}}
          VAULT_TOKEN: {{vault-token}}
          CONCOURSE_TEAM: {{concourse_team}}
          BOSH_CLIENT: ((bosh_client)) 
          BOSH_CLIENT_SECRET: ((bosh_client_secret))
          BOSH_CA_CERT: ((bosh_ca_cert))
          BOSH_ENVIRONMENT: ((bosh_environment))
          CF_API_URL_DC1: {{cf_api_url_dc1}} 
          CF_ADMIN_PASSWORD_DC1: ((cf_admin_password_dc1))
          CF_SKIP_SSL_VALIDATION_DC1: {{cf_skip_ssl_validation_dc1}} 
          CF_API_URL_DC2: {{cf_api_url_dc2}} 
          CF_ADMIN_PASSWORD_DC2: ((cf_admin_password_dc2)) 
          CF_SKIP_SSL_VALIDATION_DC2: {{cf_skip_ssl_validation_dc2}} 
          WAVEFRONT_URL: {{wavefront_url}}
          WAVEFRONT_TOKEN: ((wavefront_token))
          FRIENDLY_HOSTNAME: {{friendly_hostname}}
          MYSQL_IPS_DC1: {{mysql_ips_dc1}}
          MYSQL_IPS_DC2: {{mysql_ips_dc2}}
          PROXY_IP_DC1: {{proxy_ip_dc1}}
          PROXY_IP_DC2: {{proxy_ip_dc2}}
          BROKER_IP_DC1: {{broker_ip_dc1}}
          BROKER_IP_DC2: {{broker_ip_dc2}}
          BACKUP_IP_DC1: {{backup_ip_dc1}} 
        inputs:
        - name: concourse-mysql-deployment
    - put: mysql-version

- name: register-broker-dc1
  plan:
    - aggregate:
      - get: mysql-version 
        passed: [deploy]
        trigger: true
      - get: concourse-mysql-deployment
    - task: register-broker		
      config:		
        platform: linux		
        image_resource:		
          type: docker-image		
          source:		
            repository: smatyukevich/docker-cfbosh
            tag: latest
        run:		
          path: concourse-mysql-deployment/ci/tasks/run-errand.sh		
        params:		
          BOSH_ERRAND: broker-registrar-vm-dc1		
          BOSH_CLIENT: ((bosh_client)) 
          BOSH_CLIENT_SECRET: ((bosh_client_secret))
          BOSH_CA_CERT: ((bosh_ca_cert))
          BOSH_ENVIRONMENT: ((bosh_environment))
        inputs:		
        - name: concourse-mysql-deployment


- name: register-broker-dc2
  plan:
    - aggregate:
      - get: mysql-version 
        passed: [register-broker-dc1]
        trigger: true
      - get: concourse-mysql-deployment
    - task: register-broker		
      config:		
        platform: linux		
        image_resource:		
          type: docker-image		
          source:		
            repository: smatyukevich/docker-cfbosh
            tag: latest
        run:		
          path: concourse-mysql-deployment/ci/tasks/run-errand.sh		
        params:		
          BOSH_ERRAND: broker-registrar-vm-dc2		
          BOSH_CLIENT: ((bosh_client)) 
          BOSH_CLIENT_SECRET: ((bosh_client_secret))
          BOSH_CA_CERT: ((bosh_ca_cert))
          BOSH_ENVIRONMENT: ((bosh_environment))
        inputs:		
        - name: concourse-mysql-deployment

- name: backup 
  plan:
    - aggregate:
      - get: concourse-mysql-deployment
      - get: daily
        trigger: true
    - task: backup		
      config:		
        platform: linux		
        image_resource:		
          type: docker-image		
          source:		
            repository: smatyukevich/docker-cfbosh
            tag: latest
        run:		
          path: concourse-mysql-deployment/ci/tasks/backup.sh		
        params:		
          BOSH_ERRAND: broker-registrar-vm-dc2		
          BOSH_CLIENT: ((bosh_client)) 
          BOSH_CLIENT_SECRET: ((bosh_client_secret))
          BOSH_CA_CERT: ((bosh_ca_cert))
          BOSH_ENVIRONMENT: ((bosh_environment))
        inputs:		
        - name: concourse-mysql-deployment

