concourse-mysql-deployment-git-url: https://github.com/s-matyukevich/concourse-mysql-deployment.git
cf-mysql-release-url: https://github.com/cloudfoundry/cf-mysql-release.git
cf_mysql_release_tag: v36.14.0
cf_mysql_broker_url: https://github.com/s-matyukevich/cf-mysql-broker.git
