concourse-mysql-deployment-git-url: https://github.com/s-matyukevich/concourse-mysql-deployment.git
#cf_mysql_release_url: https://github.com/cloudfoundry/cf-mysql-release.git
#cf_mysql_release_tag: v36.14.0
cf_mysql_release_url: https://github.com/s-matyukevich/cf-mysql-release.git
cf_mysql_release_tag: bootstrap 
cf_mysql_broker_url: https://github.com/s-matyukevich/cf-mysql-broker.git
wavefront_proxy_release_url: https://github.com/s-matyukevich/cloud-foundry-release/releases/download/v0.0.1/wavefront-proxy-1.tgz
telegraf_agent_release_url: https://github.com/s-matyukevich/telegraf-agent-bosh-release.git
stemcell_url: https://bosh.io/d/stemcells/bosh-vsphere-esxi-ubuntu-trusty-go_agent?v=
wavefront_url: https://try.wavefront.com/api
friendly_hostname: mysql-proxy 
stemcell_version: 3586.24
cf_api_url_dc1: https://api.us07-6-pcf3-system.oc.vmware.com
cf_skip_ssl_validation_dc1: true
cf_api_url_dc2: https://api.us07-6-pcf2-system.oc.vmware.com
cf_skip_ssl_validation_dc2: true
mysql_ips_dc1: "[10.191.9.130,10.191.9.131]"
mysql_ips_dc2: "[10.165.19.130,10.165.19.131]"
proxy_ip_dc1: 10.191.9.132
proxy_ip_dc2: 10.165.19.132
broker_ip_dc1: 10.191.9.133
broker_ip_dc2: 10.165.19.133
